### PR TITLE
Blog app: add devise

### PR DESCRIPTION
**Pull request by obibaadoma**
# Project Requirements

## Authentication Refactoring
- Remove the current_user method in ApplicationController, as Devise will provide the necessary functionality.

## Devise Integration
- Install and set up Devise for user authentication.

## User Registration
- Implement the ability for users to register for a new account.

## User Login
- Users should be able to log in using a combination of email and password.

## Password Storage
- Ensure that hashed passwords are securely stored in the database.

## Email Confirmation
- Implement a mechanism to confirm user email addresses.

## Password Reset
- Provide functionality for users to reset their passwords.

## View Modification
- Modify the views in Devise for registration and login to match the wireframes provided in the Sneak Peek.
- Apply styling to the views to maintain consistency with the overall project design.

### CODE REVIEW

**Review by V-Blaze — CHANGES_REQUESTED** [review]
Hi @obibaadoma, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

dcentl8-9b96e129-9725-401b-ac34-2feb990202a0

## Invalid Code Review Request

## You have submitted a project, that does not have commits from your partners. This is is a pair programming task and therefore each student need to contribute and commit to this branch.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by julie-ify** [comment]
Hi @obibaadoma, @EvansSnave and @fmanimashaun,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

* The last two team members did not make meaningful contributions to this project. Kindly redo the project with meaningful commits related to the project guidelines.

* In the new PR, also ensure there are not 5000+ files changed. You should use `.gitignore` properly, as files of that amount make review next to impossible.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by zeff96 — COMMENTED** [review]
## STATUS: INVALID CODE REVIEW 🛑
Hi @obibaadoma , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

The current project pull request lacks substantial contributions from your partner, as highlighted by previous reviewers. Please close this PR (without merging) and let's kick off a new one with meaningful code contributions from all partners. 🚀

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by LionRouge1 — COMMENTED** [review]
Hi @Team, 

done

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, where the difference number of commits between the partners is too much, as highlighted by previous reviewers. Please close this PR (without merging) and create a new one in which all the partners have contributed equally to the project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by DammyShittu** [comment]
Hi @obibaadoma,

While you made a great effort in this project, I cannot proceed to review your code.

## Invalid Code Review Request

### Kindly verify your submissions. This PR is closed.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request closed without merging**
